version: '3.2'

services:
  boagent:
    image: ghcr.io/boavizta/boagent:greenhack22
    environment:
      BOAVIZTAPI_ENDPOINT: "http://boaviztapi:5000"
      DEFAULT_LIFETIME: 5.0
      HARDWARE_FILE_PATH: "/home/boagent/hardware_data.json"
      POWER_FILE_PATH: "/app/data/power_data.json"
      AZURE_LOCATION: francesouth
        #user: boagent
    depends_on:
      - boaviztapi
      - scaphandre
    ports: 
      - "8000:8000"
    networks:
      - boagent-network
    volumes:
      - "/proc:/proc"
      - "/sys:/sys:ro"
      - "powerdata:/app/data:ro"
      - "./db:/app/db"
      - "../boaviztapi/boaviztapi:/app/boaviztapi"
      - "/etc/crontab:/etc/crontab"

  scaphandre:
    image: hubblo/scaphandre:greenhack22
    volumes:
      - type: bind
        source: /proc
        target: /proc
      - type: bind
        source: /sys/class/powercap
        target: /sys/class/powercap
      - "powerdata:/app/data:rw"
    command: [ "--no-header", "json", "-s", "10", "--max-top-consumers", "0",  "-f", "/app/data/power_data.json" ]                         
    networks:
      - boagent-network

  watcher:
    image: bpetit/platypus
    depends_on:
      - boagent
    networks:
      - boagent-network
    
  boaviztapi:
    image: ghcr.io/boavizta/boaviztapi:greenhack22
    ports: 
      - "127.0.0.1:5000:5000"
    networks:
      - boagent-network
    volumes:
      - "../boaviztapi/boaviztapi:/app/boaviztapi"

volumes:
  powerdata: {}

networks:
  boagent-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.33.0/24
